---
# Launch an instance and then add a volume if not already attached
#    Volume will be created with the given name if not already created.
#    Nothing will happen if the volume is already attached.
- name: Playbook to attach EBS with EC2 and encrypt it
  hosts: xxxxxx
  become: True
  tasks:
   - name: Create and Register Ec2
     ec2:
       keypair: "{{ keypair }}"
       image: "{{ image }}"
       zone: YYYYYY
       id: my_instance
       wait: yes
       count: 1
       register: ec2
       notify:
         - attach_ebs
handlers:
   - name: attach_ebs
     ec2_vol:
       instance: "{{ item.id }}"
       name: my_existing_volume_Name_tag
       device_name: /dev/xvdf
       loop: "{{ ec2.instances }}"
       encrypted: yes
       delete_on_termination: no
       register: ec2_vol
       
 # ansible-playbook PlaybookEc2.yml
...
